"""serpentrum.pymol_bridge — the single cmd-seam module (ARCHITECTURE.md sec 2:
"the ONLY module (besides controller/input) importing pymol.cmd").

BRIDGE purity class (03-01): ``from pymol import cmd`` at module level is
allowed here and ONLY here. PyQt5/numpy are banned anywhere (Qt stays in
GUI modules; pure modules do the math). ``.exec_()`` is banned (the bridge
builds no dialogs). Relative imports of pure modules (cgo_build,
setup_logic) are purity-exempt. setloader is NOT imported here — molecule
records arrive as arguments to ``materialize`` (the bridge never parses
SDFs itself; that is molfile/setloader's PURE job from 03-02/03-04).

Why the bridge is THIN: it cannot be WSL-unit-tested (module-level
``from pymol import cmd`` — no pymol in WSL python3.6). All pure logic
(parsing, gating, record building, box-CGO float construction, setup
schema) already lives in molfile/setloader/cgo_build/setup_logic. The
bridge is just the cmd-calling surface that turns pure data into PyMOL
viewer objects. Its correctness is pinned by the headless Windows PyMOL
smoke (smoke/03_viewer_bridge_smoke.py, sentinel-flushed) and finalized
by the phase's human-verify (03-08).

Fresh-process cleanup contract (INFRA-04 / SC5): ``.pse`` session files
save viewer objects (CGO + molecules) but NO plugin Python state
(PITFALLS.md 8.3). After a .pse reload in a FRESH process, no controller
or game state exists. Therefore ``cleanup_srp`` is a PURE FUNCTION OF
OBJECT NAMES: it takes no controller/game-state/anchor arguments, counts
``srp_*`` objects via ``cmd.get_names``, deletes with the ``srp_*`` name
pattern, and returns the count. The identical code path works from a live
dialog AND from a fresh process after .pse reload.

srp_ PREFIX RESERVATION: the ``srp_`` object-name prefix is RESERVED for
game-generated PyMOL objects. Any user object named ``srp_*`` is treated
as game-generated and removed by Cleanup — PyMOL has no undo (PITFALLS.md
F17), so users must not name their own objects ``srp_*``. This reservation
IS the INFRA-04 contract: in a fresh process the plugin cannot distinguish
game-created ``srp_*`` from user-created ``srp_*``, so any ``srp_*`` object
is game-generated BY POLICY. Documented in AGENTS.md.

Camera (research sec 5): Phase 3 did ONE-SHOT ``cmd.zoom('srp_*')`` +
``cmd.refresh()`` ONLY (setup preview framing, SC2). Phase 4 OWNS GAME-02
— the locked 2D camera — so ``cmd.set('ortho')``, ``cmd.get_view`` /
``cmd.set_view``, and ``cmd.button`` rebinds are now legal HERE
(04-RESEARCH-gameloop.md Q3; 03-RESEARCH-viewer-bridge.md sec 5.2: the
Phase-3 "zoom only" boundary was phase-scoped). ``lock_camera`` /
``unlock_camera`` implement the play lock; ``frame_scene`` stays the
one-shot setup framing. NO per-tick reframing (pitfall 14).
``zoom=0`` on every load so only ``frame_scene`` frames.

python3.6 syntax (%-formatting). No logging, no prints (the GUI owns
status reporting). Every function is <= ~15 lines.
"""

from pymol import cmd

from . import cgo_build
from . import setup_logic

# --- namespace + display constants -----------------------------------------
# SRP_PREFIX: every game-generated PyMOL object name starts with this.
#   RESERVED — see module docstring + AGENTS.md. Cleanup deletes srp_* by
#   name pattern; the prefix is the fresh-process recovery contract.
SRP_PREFIX = 'srp_'

# BOX_DISPLAY_Z: shallow z-depth for 2D-plane perception (STACK.md sec 3,
#   2D variant: "rectangle + shallow depth"). setup_logic.BOX_PRESETS owns
#   xy extents only; z is display-only and lives here (research sec 5.3).
BOX_DISPLAY_Z = 5.0

# Canonical srp_* object names for the Phase-3 scene (srp_box + srp_head).
BOX_NAME = 'srp_box'   # CGO boundary box (cgo_build.box_cgo -> cmd.load_cgo)
HEAD_NAME = 'srp_head'  # head molecule (cmd.load object=, spheres rep)

# Default box appearance. Linewidth 3.0 (thicker than cgo_build's 2.0
# default) so the boundary box is clearly visible on a dark background.
DEFAULT_BOX_COLOR = (1.0, 0.4, 0.1)   # warm orange (visible on dark bg)
DEFAULT_BOX_LINEWIDTH = 3.0


def load_molecule(path, srp_name=HEAD_NAME, zoom=0):
    """Load a molecule file directly into the srp_* namespace.

    ``cmd.load(path, object=srp_name, zoom=zoom)`` — load-time naming lands
    the object directly under the srp_ prefix (no set_name / create copy
    needed; verified bioCHEMeleon demos.py:194,501,547). Never loads into a
    non-srp name from here; never mutates user objects (ARCHITECTURE.md
    Pattern 4). Returns the object name.
    """
    cmd.load(path, object=srp_name, zoom=zoom)
    return srp_name


def load_box(preset, color=DEFAULT_BOX_COLOR, linewidth=DEFAULT_BOX_LINEWIDTH):
    """Build + load the boundary-box CGO as ``srp_box``.

    Reads ``setup_logic.BOX_PRESETS[preset]`` for the xy extents, extends
    to ``+/- BOX_DISPLAY_Z`` in z (display-only depth), builds the CGO
    float list via ``cgo_build.box_cgo``, and loads it with
    ``cmd.load_cgo(..., zoom=0)``. Unknown preset -> ValueError naming it.
    Returns ``BOX_NAME``.
    """
    try:
        (x0, y0), (x1, y1) = setup_logic.BOX_PRESETS[preset]
    except KeyError:
        raise ValueError("unknown box preset %r" % (preset,))
    min_corner = (x0, y0, -BOX_DISPLAY_Z)
    max_corner = (x1, y1, BOX_DISPLAY_Z)
    cmd.load_cgo(
        cgo_build.box_cgo(min_corner, max_corner, color, linewidth),
        BOX_NAME, zoom=0)
    return BOX_NAME


def place_head(srp_name=HEAD_NAME):
    """Center the head molecule at the box origin (0, 0, 0).

    Computes the loaded molecule's centroid via ``cmd.get_extent`` (returns
    ``[[min_x, min_y, min_z], [max_x, max_y, max_z]]`` in PyMOL 2.5;
    centroid = midpoint of each axis) and translates by its negative. All
    BOX_PRESETS are symmetric about (0,0,0) (setup_logic.py:63-67), so box
    center = origin.
    """
    ext = cmd.get_extent(srp_name)
    (min_x, min_y, min_z), (max_x, max_y, max_z) = ext
    cx = (min_x + max_x) / 2.0
    cy = (min_y + max_y) / 2.0
    cz = (min_z + max_z) / 2.0
    cmd.translate([-cx, -cy, -cz], srp_name)


def cleanup_srp():
    """Delete all ``srp_*`` objects — fresh-process-safe (INFRA-04 / SC5).

    Pure function of object names: NO controller / game-state / anchor
    arguments, NO state reads. Counts ``srp_*`` objects via
    ``cmd.get_names('public_objects')`` BEFORE the delete, deletes with
    the ``srp_*`` name pattern (idempotent — backup.py:42,49), returns the
    count. Identical code path from a live dialog AND a fresh process
    after .pse reload (PITFALLS.md 8.3: viewer objects survive, plugin
    state does not).
    """
    before = [n for n in cmd.get_names('public_objects')
              if n.startswith(SRP_PREFIX)]
    cmd.delete(SRP_PREFIX + '*')
    return len(before)


def frame_scene():
    """One-shot framing: ``cmd.zoom('srp_*')`` + ``cmd.refresh()``.

    Called once after materialize so the user sees the box+head (SC2).
    NOT a locked camera — Phase 4 owns GAME-02 (fixed projection,
    view-matrix, view-lock during play). zoom=0 on every load ensures
    only this call frames.
    """
    cmd.zoom(SRP_PREFIX + '*')
    cmd.refresh()


# --- Phase 4: per-tick movement + locked camera (GAME-02) -------------------
# Mouse-lock buttons: every rotate/zoom/pan/select combo -> action 'none'.
_LOCK_BUTTONS = ('left', 'middle', 'right', 'wheel')
_LOCK_MODS = ('None', 'Shft', 'Ctrl', 'CtSh')


def move_head_delta(dx, dy, dz=0.0):
    """Translate srp_head by (dx, dy, dz) in MODEL axes (camera=0).

    Atomic-coordinate translate (the object=None path), so atomic coords
    stay = engine truth (Phase-5 xtb coord handoff). camera=0 = model
    axes — camera=1 would desync from engine truth if the view were ever
    non-axis-aligned (gameloop pitfall 4). Zero drift verified:
    5 * [0.3,0,0] -> exactly [1.5,0,0] (probe TL_5TICKS_0.3A, M3).
    dz stays 0.0 (2D plane contract, gameloop P3). Called once per
    ('moved',) tick. NEVER get_object_ttt for verification (segfaults,
    M5) — use get_extent.
    """
    cmd.translate([float(dx), float(dy), float(dz)], HEAD_NAME, camera=0)


def lock_camera():
    """Lock the camera to a 2D ortho view of the box (GAME-02).

    Returns the saved state for unlock_camera(). Called at _begin_play
    (plan 04-08). Frames the WHOLE box, never the head (pitfalls 5/14 —
    no per-tick re-zoom). button 'none' = action code 22
    (controlling.py:80); all 16 combos. The mouse lock does NOT touch
    the keyboard wizard (independent mechanisms, C5).
    """
    saved = {'ortho': cmd.get('ortho'), 'view': cmd.get_view()}
    cmd.set('ortho', 'on')
    cmd.zoom(BOX_NAME)
    cmd.refresh()
    for btn in _LOCK_BUTTONS:
        for mod in _LOCK_MODS:
            cmd.button(btn, mod, 'none')
    return saved


def unlock_camera(saved):
    """Restore mouse defaults + ortho + the 18-float view.

    Called by EVERY teardown path (win/lose/restart/pause-to-setup/
    dialog-close — wired in plan 04-08); idempotent via the None guard.
    cmd.mouse() re-applies the CURRENT button_mode's defaults
    (controlling.py:648-676) — caveat C4: restores MODE defaults, not
    per-user customizations (acceptable for v1, document in Help).
    """
    if saved is None:
        return
    cmd.mouse()
    cmd.set('ortho', saved['ortho'])
    cmd.set_view(saved['view'])
    cmd.refresh()


def object_exists(name):
    """True iff ``name`` is a public PyMOL object — guarded scene checks.

    Uses the PROVEN 2.5.0 type 'public_objects' (03-06; 'all_objects'
    raises). E.g. re-centering srp_head on Restart when the scene may
    not exist (plan 04-05).
    """
    return name in cmd.get_names('public_objects')


def _select_head_record(setup, records, errors):
    """Pick the head molecule record per setup['head_molecule'].

    Empty records -> advisory error + None (box-only scene). 'random' ->
    records[0] (Phase-3 placeholder; true randomization is game-start,
    Phase 4). A named id -> the matching record, or advisory error + None
    if no match. Appends to ``errors`` in-place; never raises.
    """
    if not records:
        errors.append('no head molecule loaded — upload a set or '
                      'provide demo data')
        return None
    head_id = setup.get('head_molecule', 'random')
    if head_id == 'random':
        return records[0]
    for record in records:
        if record.get('id') == head_id:
            return record
    errors.append("head molecule '%s' not in the loaded set" % (head_id,))
    return None


def materialize(setup, records, head_m16=None):
    """The Apply path (03-RESEARCH-setup-ui.md sec 6.3).

    1. ``cleanup_srp`` first (removes leftover srp_* from a prior game).
    2. ``load_box(setup['box_preset'])`` (ValueError -> error + early
       return; nothing loads).
    3. Head selection via ``_select_head_record``: empty records or no
       match -> box-only scene (still framed). 'random' -> records[0].
       Named id -> that record.
    4. On a selected record: ``load_molecule``, the OPTIONAL edge-on
       ``head_m16`` transform, ``cmd.show('spheres')``, ``place_head``.
       EDGE-ON FIRST (locked 03-08 + 04-07): the transform runs BEFORE
       ``place_head`` so the extent being centered is the canonical one
       (Pattern 1 of 05-RESEARCH-pymol-mechanics.md). ``head_m16`` is
       computed by the CALLER from pure modules (molfile + orientation)
       — the bridge never parses SDFs.
    5. ``frame_scene`` (one-shot zoom+refresh — the box is visible even
       when no head loads).
    Returns a list of error strings (empty on full success).
    """
    errors = []
    cleanup_srp()
    try:
        load_box(setup['box_preset'])
    except ValueError as exc:
        errors.append(str(exc))
        return errors
    record = _select_head_record(setup, records, errors)
    if record is not None:
        load_molecule(record['file'], HEAD_NAME)
        if head_m16 is not None:
            cmd.transform_selection(HEAD_NAME, head_m16)
        cmd.show('spheres', HEAD_NAME)
        place_head(HEAD_NAME)
    frame_scene()
    return errors


# --- Phase 5: placement, sweep, completion seams (G7 part 1) ----------------
# Every function below is a THIN cmd forwarder — matrix math STAYS in the
# pure layer (orientation.py builds the m16; the bridge never parses SDFs
# and never composes transforms). All mechanisms are researcher-VERIFIED
# (05-RESEARCH-pymol-mechanics.md probes A1/B/C/G); this section wires
# them, it does not re-spike them. smoke/07_transform_sweep_smoke.py pins
# each one live as regression.


def apply_matrix(name, m16):
    """Apply a 16-float TTT transform to object ``name``.

    ``cmd.transform_selection(name, m16)``. Layout is PyMOL's TTT
    (homogenous=0), verified end-to-end by probe A1 (max err 1.2e-07 A):
    rows 0-2 cols 0-2 = row-major 3x3 R applied to the COLUMN vector;
    col 3 (m[3], m[7], m[11]) = post-translation; the bottom row
    (m[12], m[13], m[14]) = pre-translation applied BEFORE R. So
    ``y = R . (x + pre) + t``. The matrix is built in the PURE layer;
    the bridge only forwards. Atomic-coordinate writes regenerate
    representations automatically (editing.py:1962-1988). NEVER verify
    by reading back with cmd.get_object_ttt — it SEGFAULTS
    (04 probe M5, pitfall P5-2); get_extent/get_model are safe.
    """
    cmd.transform_selection(name, m16)


def sweep_chain(delta_deg, pivot_xy, selection='srp_head or srp_seg_*'):
    """Rigidly sweep the whole chain: ONE cmd.rotate per ('turning',) tick.

    ``cmd.rotate('z', delta, selection, camera=0, origin=[hx,hy,0])`` —
    rigid multi-object rotation with atomic-coordinate writes (probe B:
    10 objects ~0.4 ms; internal geometry preserved <5e-07 A). ``origin=``
    is MANDATORY: the default is the current VIEW centre, not the head
    (pitfall P5-4, editing.py:1807-1808). ``camera=0`` = model axes —
    camera=1 would rotate about a camera-space axis (the
    gameloop-pitfall-4 desync class). delta > 0 = CCW about +z, matching
    the engine's ``_rotate_xy`` sign. The selection INCLUDES srp_head:
    the pivot is the head centre, so the head rotates in place, keeping
    its ring normal on the chain axis (Pattern 2, probe B). CGO members
    (srp_box) are harmless — CGOs are not transformed (pitfall P5-7,
    probe C2).
    """
    cmd.rotate('z', float(delta_deg), selection, camera=0,
               origin=[float(pivot_xy[0]), float(pivot_xy[1]), 0.0])


def zoom_chain(selection='srp_head or srp_seg_*'):
    """Frame the completed chain: ``cmd.zoom`` + ``cmd.refresh`` (GAME-09).

    MUST run AFTER unlock_camera: unlock ends with ``cmd.set_view``
    (18 floats including scale/position), which clobbers any prior zoom
    (pitfall P5-3, Pattern 4 completion ordering). The saved default
    view looks down -z at the xy plane, so this zoom frames the snake
    in 2D without ``cmd.orient`` (probe G3).
    """
    cmd.zoom(selection)
    cmd.refresh()


def materialize_pickup(path, name, m16):
    """Spawn ONE pickup object edge-on at its spawn centroid, as STICKS.

    ``cmd.load(path, object=name, zoom=0)`` + ONE
    ``cmd.transform_selection(name, m16)`` + ``cmd.show('sticks', name)``.
    ``m16`` is composed by the CALLER from pure modules as
    ``orientation.matrix_rt(R_edge, centroid, pre)`` —
    ``y = R.(x + pre) + t`` lands the ring centroid at the spawn centroid
    (the bridge never parses SDFs; the caller did). Pickups render as
    STICKS (GAME-03; the head stays spheres). Returns ``name``.
    """
    cmd.load(path, object=name, zoom=0)
    cmd.transform_selection(name, m16)
    cmd.show('sticks', name)
    return name


def reload_head(path, m16=None):
    """Restore srp_head's canonical pose by RELOADING its file.

    ``cmd.delete`` (when the object exists) -> ``cmd.load(path,
    object=HEAD_NAME, zoom=0)`` -> optional ONE ``cmd.transform_selection
    (HEAD_NAME, m16)`` (the Apply-time edge-on matrix) -> ``cmd.show``
    spheres (view parity with ``materialize``) -> ``place_head`` extent
    re-center.

    This is THE begin_game pose reset (gui_game._reset_head_viewer; the
    live-verified perpendicular-stack fix): re-APPLYING the edge-on m16
    to the current object is INVALID — an m16 encodes the transform of
    the RAW SDF coords, so applying it a second time double-rotates the
    ring plane (measured on benzene: displayed head ring normal lands at
    exactly 90.00 degrees off the placed slab's normal — the T-shape
    the user saw at the 05-16 checkpoint). Reloading from the record's
    own file re-canonicalizes deterministically whether the round is a
    first start (Apply already edge-on'd) or a Restart after sweeps
    (sweeps rotate atomic coords; the file pose is unambiguous truth).
    m16=None keeps the head_m16=None Apply parity (upload heads).
    """
    if object_exists(HEAD_NAME):
        cmd.delete(HEAD_NAME)
    cmd.load(path, object=HEAD_NAME, zoom=0)
    if m16 is not None:
        cmd.transform_selection(HEAD_NAME, m16)
    cmd.show('spheres', HEAD_NAME)
    place_head(HEAD_NAME)
    return HEAD_NAME


def delete_pickups():
    """Delete every uneaten pickup: pattern delete ``srp_pickup_*``.

    Verified G4; idempotent. Used by teardown AND by the completion
    flow (stray pickups leave the framed scene). ``srp_seg_*`` /
    ``srp_head`` are untouched — the pattern matches pickups only.
    """
    cmd.delete('srp_pickup_*')


def rename_pickup(old, new):
    """Rename a pickup object to its captured ``srp_seg_<n>`` name.

    ``cmd.set_name(old, new)`` — bog-standard naming.py API (not probed
    in research; smoke 07 verifies it live). Keeps the atom set
    identical to what the player saw. Fallback if it ever fails:
    delete + load fresh + apply the composed matrix via ``apply_matrix``
    — but set_name is the shipping path (research Open Question 4).
    """
    cmd.set_name(old, new)


def chain_object_names():
    """Sorted public object names of the chain (head + segments).

    Objects whose name starts ``srp_head`` or ``srp_seg``, via
    ``cmd.get_names('public_objects')`` — the PROVEN 2.5.0 type
    (03-06; 'all_objects' raises). Completion-ONLY read (framing / xyz
    handoff); NEVER per tick — the engine tracks all positions as
    floats and PyMOL is a pure renderer (Pattern 5).
    """
    names = cmd.get_names('public_objects')
    return sorted(n for n in names
                  if n.startswith('srp_head') or n.startswith('srp_seg'))
